### ISSUE TITLE
Quest collection detailed view

### ISSUE THREAD

**Issue by lczx** [fdi2-epsilon/teams-game#14]
Create a new activity to show a list of quests inside a collection, so the user won't need to load a quest and scroll tabs.

**Comment by Vik28** [comment]
In fase di sviluppo

**Comment by lczx** [comment]
@Vik28 se intendi fare una *Pull Request* per i cambiamenti nel tuo branch [`list-levels-activity`](../tree/list-levels-activity), sappi che puoi usare keyword come `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, ... nella descrizione seguito dall'ID di questo issue (#14) per chiuderlo automaticamente al merge; proprio come ho fatto [qui](../pull/4).
