### ISSUE TITLE
Pannello introduttivo al primo avvio

### ISSUE THREAD

**Issue by Vik28** [fdi2-epsilon/teams-game#7]
L'utente deve poter visualizzare, al primo avvio, una schermata che lo introduca al funzionamento dell'applicazione.

**Comment by lczx** [comment]
@fdi2-epsilon/owners questa non dovrebbe essere difficile da fare, la schermata c'è già, basta solo disabilitarla una volta cliccato *Ok*, consiglio di dare un'occhata qui per come salvare lo stato: https://developer.android.com/training/basics/data-storage/shared-preferences.html
