### ISSUE TITLE
Identificazione veloce delle storie recenti

### ISSUE THREAD

**Issue by Vik28** [fdi2-epsilon/teams-game#9]
L'utente deve poter individuare immediatamente la collezione di enigmi (campagna) giocata più recentemente, averne una immagine e descrizione rapida per un riconoscimento ancora più immediato.

**Comment by lczx** [comment]
Già risolto usando più carte con immagini nella schermata principale, carte più grosse indicano campagne giocate più di recente; quella più grande di tutti è l'ultima giocata ed è sempre in cima alla lista.

**Comment by lczx** [comment]
Riaperto perchè la soluzione è solamente a livello interfaccia grafica, bisogna implementare un semplice algoritmo che decida a quali campagne dare più evidenza.
